// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2gxn2JXh6YhUZ9J3UAxtkeDJ0tdBSvLw',
    appId: '1:351577286503:web:b5268f3936ebd5279e31c2',
    messagingSenderId: '351577286503',
    projectId: 'leadkart-ai',
    authDomain: 'leadkart-ai.firebaseapp.com',
    storageBucket: 'leadkart-ai.appspot.com',
    measurementId: 'G-G3YMLN5SB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFsq6Y4XLeYqnLQbrEEqumBbbu352y2Rg',
    appId: '1:351577286503:android:8275e8bebc8279569e31c2',
    messagingSenderId: '351577286503',
    projectId: 'leadkart-ai',
    storageBucket: 'leadkart-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYM_YUrn6Yt9aiosUFr6NcRkqwCfixKS4',
    appId: '1:351577286503:ios:03722bfbbec269c69e31c2',
    messagingSenderId: '351577286503',
    projectId: 'leadkart-ai',
    storageBucket: 'leadkart-ai.appspot.com',
    iosBundleId: 'com.example.leadKartClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYM_YUrn6Yt9aiosUFr6NcRkqwCfixKS4',
    appId: '1:351577286503:ios:03722bfbbec269c69e31c2',
    messagingSenderId: '351577286503',
    projectId: 'leadkart-ai',
    storageBucket: 'leadkart-ai.appspot.com',
    iosBundleId: 'com.example.leadKartClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2gxn2JXh6YhUZ9J3UAxtkeDJ0tdBSvLw',
    appId: '1:351577286503:web:6736b7f66558b82a9e31c2',
    messagingSenderId: '351577286503',
    projectId: 'leadkart-ai',
    authDomain: 'leadkart-ai.firebaseapp.com',
    storageBucket: 'leadkart-ai.appspot.com',
    measurementId: 'G-KV5EHLKKHY',
  );
}
